### ISSUE TITLE
Add getQueue command

### ISSUE THREAD

**Issue by schnabel** [OnFreund/PyVolumio#4]
Hi, 

I would like to fix the [Volumio Integration - TTS broken](https://github.com/home-assistant/core/issues/45337). I think it is a good idea to be able to resume playback of the current queue after TTS is done. Either hardcoded or like the sonos integration with a snapshot of the current state. Both solutions need to be able to get the current queue and state.

**Comment by schnabel** [comment]
@OnFreund Thank you for accepting the PR. Are you still interested in your Volumio Integration?

**Comment by OnFreund** [comment]
Yes, still interested, just have significantly less capacity these days

**Comment by schnabel** [comment]
Good to hear! Than I will start fixing the TTS bug. Hope you will find the time to review :-).

**Comment by OnFreund** [comment]
As long as it's not a monster PR I should be able to find time to review :)
